### PR TITLE
Adds some tests

### PR DESCRIPTION
**Pull request by Bjorn248**
Tries to help with issue #3 

Generates a bunch of mp3 and a bunch of golden files (expected output). It seems that this tool can't really handle VBR files at all, or MPEG layer 2/2.5. I think 179 out of 198 tests fail currently. So yeah...only 19 tests pass. I think I'm generating "OK" mp3s with `ffmpeg` and `lame`, since `ffprobe` seems to be able to parse them.

### CODE REVIEW

**Comment by betamike** [comment]
Hey @Bjorn248 sorry for taking so long on this! I updated the project to go modules so it works with the latest version of Go, you should rebase this on the latest commit.

I updated the makefile so it automatically generates the test files (and added `.PHONY' so test and build work even when make thinks they haven't changed):

```
diff --git a/Makefile b/Makefile
index 86bb4f8..997c42e 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,8 @@
-test:
+.PHONY: test build
+
+test/files:
+       cd test && ./generate_mp3s.sh && ./generate_golden_files.sh
+test: test/files
        go test ./...
 build:
        go build -o bin/mp3inspect inspector.go
```

**Comment by Bjorn248** [comment]
@betamike I went ahead and rebased off your branch and squashed all my commits into one since it was getting messy. Also applied your diff to the Makefile. Does this need anything else?

**Review by betamike — APPROVED** [review]
Suuuper late but thanks so much @Bjorn248!

**Comment by Bjorn248** [comment]
@betamike haha, is this related to the fact that I switched to `fq` instead of `xxd` yesterday or is that just a coincidence?

**Comment by betamike** [comment]
@Bjorn248 haha nope, I just wasn't checking my Github notifications frequently :D

**Pull request merged**
